const LangService = function ($filter, $q, localStorageService) {
  const service = {
    getLanguagesList,
    getNativeLanguages,
    getUserLanguages,
    setUserLanguages,
  };

  const countryLanguagesList = {
    Q889: ['ps'],
    Q222: ['sq'],
    Q262: ['ar'],
    Q228: ['ca'],
    Q916: ['pt'],
    Q781: ['en'],
    Q414: ['es'],
    Q399: ['hy'],
    Q408: ['en'],
    Q40: ['de'],
    Q227: ['az'],
    Q398: ['ar'],
    Q902: ['bn'],
    Q244: ['en'],
    Q184: ['ru', 'be'],
    Q31: ['nl', 'fr', 'de'],
    Q242: ['en'],
    Q962: ['fr'],
    Q917: ['dz'],
    Q750: ['es'],
    Q225: ['hr', 'sr', 'bs'],
    Q963: ['en'],
    Q155: ['pt'],
    Q921: ['en'],
    Q219: ['bg'],
    Q965: ['fr'],
    Q967: ['fr', 'en'],
    Q424: ['km'],
    Q1009: ['fr', 'en'],
    Q1011: ['pt'],
    Q929: ['fr'],
    Q657: ['fr', 'ar'],
    Q298: ['es'],
    Q739: ['es'],
    Q970: ['fr', 'ar'],
    Q800: ['es'],
    Q224: ['hr'],
    Q241: ['es'],
    Q229: ['tr', 'el'],
    Q213: ['cs'],
    Q1008: ['fr'],
    Q974: ['fr'],
    Q977: ['fr', 'ar'],
    Q784: ['en'],
    Q786: ['es'],
    Q574: ['pt'],
    Q736: ['es'],
    Q79: ['ar'],
    Q792: ['es'],
    Q983: ['fr', 'es', 'pt'],
    Q986: ['en', 'ar', 'ti'],
    Q191: ['et'],
    Q115: ['am'],
    Q702: ['en'],
    Q55: ['nl', 'fy'],
    Q16: ['en', 'fr'],
    Q712: ['en'],
    Q33: ['fi', 'sv'],
    Q142: ['fr'],
    Q1000: ['fr'],
    Q1005: ['en'],
    Q230: ['ka'],
    Q183: ['de'],
    Q117: ['en'],
    Q41: ['el'],
    Q769: ['en'],
    Q774: ['es'],
    Q1006: ['fr'],
    Q1007: ['pt'],
    Q734: ['en'],
    Q790: ['fr', 'ht'],
    Q783: ['es'],
    Q28: ['hu'],
    Q189: ['is'],
    Q668: ['hi', 'en'],
    Q252: ['id'],
    Q794: ['fa'],
    Q796: ['ar', 'ku'],
    Q27: ['en'],
    Q801: ['he'],
    Q38: ['it'],
    Q766: ['en'],
    Q17: ['ja'],
    Q810: ['ar'],
    Q232: ['kk'],
    Q114: ['en', 'sw'],
    Q29999: ['nl'],
    Q710: ['en'],
    Q817: ['ar'],
    Q813: ['ru', 'ky'],
    Q819: ['lo'],
    Q211: ['lv'],
    Q822: ['ar'],
    Q1013: ['en', 'st'],
    Q1014: ['en'],
    Q1016: ['ar'],
    Q347: ['de'],
    Q37: ['lt'],
    Q32: ['fr', 'de', 'lb'],
    Q1019: ['fr', 'mg'],
    Q1020: ['en', 'ny'],
    Q833: ['en'],
    Q826: ['dv'],
    Q912: ['fr'],
    Q233: ['en', 'mt'],
    Q709: ['en', 'mh'],
    Q1025: ['ar'],
    Q1027: ['fr', 'en'],
    Q96: ['es'],
    Q217: ['mo'],
    Q235: ['fr'],
    Q711: ['mn'],
    Q236: ['hr', 'sq', 'sr', 'bs'],
    Q1028: ['ar'],
    Q1029: ['pt'],
    Q836: ['my'],
    Q1030: ['en'],
    Q697: ['en', 'na'],
    Q837: ['ne'],
    Q664: ['en', 'mi'],
    Q811: ['es'],
    Q1032: ['fr'],
    Q1033: ['en'],
    Q423: ['ko'],
    Q20: ['nn', 'nb'],
    Q842: ['ar'],
    Q843: ['ur', 'en'],
    Q695: ['en'],
    Q804: ['es'],
    Q691: ['en', 'ho', 'tpi'],
    Q733: ['es', 'gn'],
    Q419: ['es', 'ay'],
    Q928: ['en'],
    Q36: ['pl'],
    Q45: ['pt'],
    Q846: ['ar'],
    Q221: ['mk'],
    Q971: ['fr'],
    Q218: ['ro'],
    Q159: ['ru'],
    Q1037: ['fr', 'en', 'rw'],
    Q763: ['en'],
    Q760: ['en'],
    Q757: ['es', 'en'],
    Q683: ['en', 'sm'],
    Q238: ['it'],
    Q1039: ['pt'],
    Q1041: ['fr'],
    Q403: ['sr'],
    Q1042: ['fr', 'en', 'crs'],
    Q1044: ['en'],
    Q334: ['en', 'ta', 'ms'],
    Q214: ['sk'],
    Q215: ['sl'],
    Q685: ['en'],
    Q1045: ['so', 'ar'],
    Q258: ['en', 'zu'],
    Q884: ['ko'],
    Q958: ['en'],
    Q29: ['es'],
    Q854: ['ta', 'si'],
    Q1049: ['en', 'ar'],
    Q730: ['nl'],
    Q1050: ['en', 'ss'],
    Q34: ['sv'],
    Q39: ['fr', 'de', 'it'],
    Q858: ['ar'],
    Q863: ['tg'],
    Q924: ['en', 'sw'],
    Q869: ['th'],
    Q778: ['en'],
    Q945: ['fr'],
    Q678: ['en', 'to'],
    Q754: ['en'],
    Q948: ['ar'],
    Q43: ['tr'],
    Q874: ['ru', 'tk'],
    Q672: ['en', 'tvl'],
    Q1036: ['en', 'sw'],
    Q212: ['uk'],
    Q878: ['ar'],
    Q145: ['en'],
    Q30: ['en'],
    Q77: ['es'],
    Q265: ['uz'],
    Q686: ['fr', 'en', 'bi'],
    Q717: ['es'],
    Q881: ['vi'],
    Q805: ['ar'],
    Q953: ['en'],
    Q954: ['en'],
  };
  const languageList = [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'ceb', name: 'Cebuano', nativeName: 'Sinugboanong Binisaya' },
    { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
    { code: 'de', name: 'German', nativeName: 'Deutsch' },
    { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
    { code: 'fr', name: 'French', nativeName: 'Français' },
    { code: 'ru', name: 'Russian', nativeName: 'Русский' },
    { code: 'it', name: 'Italian', nativeName: 'Italiano' },
    { code: 'es', name: 'Spanish', nativeName: 'Español' },
    { code: 'war', name: 'Waray-Waray', nativeName: 'Winaray' },
    { code: 'pl', name: 'Polish', nativeName: 'Polski' },
    { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
    { code: 'ja', name: 'Japanese', nativeName: '日本語' },
    { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
    { code: 'zh-hans', name: 'Simplified Chinese', nativeName: '简体' },
    { code: 'zh-hant', name: 'Traditional Chinese', nativeName: '繁體' },
    { code: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
    { code: 'ca', name: 'Catalan', nativeName: 'Català' },
    { code: 'fa', name: 'Persian', nativeName: 'فارسی' },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
    { code: 'nb', name: 'Norwegian (Bokmål)', nativeName: 'Norsk (Bokmål)' },
    { code: 'sh', name: 'Serbo-Croatian', nativeName: 'Srpskohrvatski / Српскохрватски' },
    { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
    { code: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
    { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
    { code: 'ro', name: 'Romanian', nativeName: 'Română' },
    { code: 'cs', name: 'Czech', nativeName: 'Čeština' },
    { code: 'ko', name: 'Korean', nativeName: '한국어' },
    { code: 'sr', name: 'Serbian', nativeName: 'Српски / Srpski' },
    { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
    { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
    { code: 'eu', name: 'Basque', nativeName: 'Euskara' },
    { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto' },
    { code: 'bg', name: 'Bulgarian', nativeName: 'Български' },
    { code: 'da', name: 'Danish', nativeName: 'Dansk' },
    { code: 'min', name: 'Minangkabau', nativeName: 'Baso Minangkabau' },
    { code: 'kk', name: 'Kazakh', nativeName: 'Қазақша' },
    { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina' },
    { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն' },
    { code: 'zh-min-nan', name: 'Min Nan', nativeName: 'Bân-lâm-gú' },
    { code: 'he', name: 'Hebrew', nativeName: 'עברית' },
    { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių' },
    { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski' },
    { code: 'ce', name: 'Chechen', nativeName: 'Нохчийн' },
    { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina' },
    { code: 'et', name: 'Estonian', nativeName: 'Eesti' },
    { code: 'gl', name: 'Galician', nativeName: 'Galego' },
    { code: 'nn', name: 'Norwegian (Nynorsk)', nativeName: 'Nynorsk' },
    { code: 'uz', name: 'Uzbek', nativeName: 'O‘zbek' },
    { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
    { code: 'la', name: 'Latin', nativeName: 'Latina' },
    { code: 'be', name: 'Belarusian', nativeName: 'Беларуская' },
    { code: 'simple', name: 'Simple English', nativeName: 'Simple English' },
    { code: 'vo', name: 'Volapük', nativeName: 'Volapük' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'th', name: 'Thai', nativeName: 'ไทย' },
    { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycanca' },
    { code: 'ka', name: 'Georgian', nativeName: 'ქართული' },
    { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg' },
    { code: 'mk', name: 'Macedonian', nativeName: 'Македонски' },
    { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy' },
    { code: 'oc', name: 'Occitan', nativeName: 'Occitan' },
    { code: 'lv', name: 'Latvian', nativeName: 'Latviešu' },
    { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski' },
    { code: 'new', name: 'Newar / Nepal Bhasa', nativeName: 'नेपाल भाषा' },
    { code: 'tt', name: 'Tatar', nativeName: 'Tatarça / Татарча' },
    { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
    { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog' },
    { code: 'sq', name: 'Albanian', nativeName: 'Shqip' },
    { code: 'pms', name: 'Piedmontese', nativeName: 'Piemontèis' },
    { code: 'br', name: 'Breton', nativeName: 'Brezhoneg' },
    { code: 'be-tarask', name: 'Belarusian (Taraškievica)', nativeName: 'Беларуская (тарашкевіца)' },
    { code: 'ky', name: 'Kirghiz', nativeName: 'Кыргызча' },
    { code: 'ht', name: 'Haitian', nativeName: 'Krèyol ayisyen' },
    { code: 'zh-yue', name: 'Cantonese', nativeName: '粵語' },
    { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa' },
    { code: 'ast', name: 'Asturian', nativeName: 'Asturianu' },
    { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
    { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
    { code: 'pnb', name: 'Western Panjabi', nativeName: 'شاہ مکھی پنجابی (Shāhmukhī Pañjābī)' },
    { code: 'sco', name: 'Scots', nativeName: 'Scots' },
    { code: 'is', name: 'Icelandic', nativeName: 'Íslenska' },
    { code: 'ga', name: 'Irish', nativeName: 'Gaeilge' },
    { code: 'cv', name: 'Chuvash', nativeName: 'Чăваш' },
    { code: 'fy', name: 'West Frisian', nativeName: 'Frysk' },
    { code: 'ba', name: 'Bashkir', nativeName: 'Башҡорт' },
    { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
    { code: 'lmo', name: 'Lombard', nativeName: 'Lumbaart' },
    { code: 'my', name: 'Burmese', nativeName: 'မြန်မာဘာသာ' },
    { code: 'an', name: 'Aragonese', nativeName: 'Aragonés' },
    { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá' },
    { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
    { code: 'io', name: 'Ido', nativeName: 'Ido' },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
    { code: 'nds', name: 'Low Saxon', nativeName: 'Plattdüütsch' },
    { code: 'scn', name: 'Sicilian', nativeName: 'Sicilianu' },
    { code: 'bpy', name: 'Bishnupriya Manipuri', nativeName: 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী' },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
    { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî / كوردی' },
    { code: 'als', name: 'Alemannic', nativeName: 'Alemannisch' },
    { code: 'bar', name: 'Bavarian', nativeName: 'Boarisch' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
    { code: 'qu', name: 'Quechua', nativeName: 'Runa Simi' },
    { code: 'ia', name: 'Interlingua', nativeName: 'Interlingua' },
    { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda' },
    { code: 'ckb', name: 'Sorani', nativeName: 'Soranî / کوردی' },
    { code: 'mn', name: 'Mongolian', nativeName: 'Монгол' },
    { code: 'arz', name: 'Egyptian Arabic', nativeName: 'مصرى (Maṣrī)' },
    { code: 'bat-smg', name: 'Samogitian', nativeName: 'Žemaitėška' },
    { code: 'nap', name: 'Neapolitan', nativeName: 'Nnapulitano' },
    { code: 'wa', name: 'Walloon', nativeName: 'Walon' },
    { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig' },
    { code: 'azb', name: 'South Azerbaijani', nativeName: 'تۆرکجه' },
    { code: 'bug', name: 'Buginese', nativeName: 'Basa Ugi' },
    { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש' },
    { code: 'am', name: 'Amharic', nativeName: 'አማርኛ' },
    { code: 'map-bms', name: 'Banyumasan', nativeName: 'Basa Banyumasan' },
    { code: 'si', name: 'Sinhalese', nativeName: 'සිංහල' },
    { code: 'fo', name: 'Faroese', nativeName: 'Føroyskt' },
    { code: 'mzn', name: 'Mazandarani', nativeName: 'مَزِروني' },
    { code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
    { code: 'li', name: 'Limburgish', nativeName: 'Limburgs' },
    { code: 'hsb', name: 'Upper Sorbian', nativeName: 'Hornjoserbsce' },
    { code: 'sah', name: 'Sakha', nativeName: 'Саха тыла (Saxa Tyla)' },
    { code: 'vec', name: 'Venetian', nativeName: 'Vèneto' },
    { code: 'os', name: 'Ossetian', nativeName: 'Иронау' },
    { code: 'ilo', name: 'Ilokano', nativeName: 'Ilokano' },
    { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
    { code: 'mrj', name: 'Hill Mari', nativeName: 'Кырык Мары (Kyryk Mary)' },
    { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
    { code: 'hif', name: 'Fiji Hindi', nativeName: 'Fiji Hindi' },
    { code: 'mhr', name: 'Meadow Mari', nativeName: 'Олык Марий (Olyk Marij)' },
    { code: 'roa-tara', name: 'Tarantino', nativeName: 'Tarandíne' },
    { code: 'xmf', name: 'Mingrelian', nativeName: 'მარგალური (Margaluri)' },
    { code: 'nah', name: 'Nahuatl', nativeName: 'Nāhuatl' },
    { code: 'eml', name: 'Emilian-Romagnol', nativeName: 'Emiliàn e rumagnòl' },
    { code: 'pam', name: 'Kapampangan', nativeName: 'Kapampangan' },
    { code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी' },
    { code: 'ps', name: 'Pashto', nativeName: 'پښتو' },
    { code: 'nso', name: 'Northern Sotho', nativeName: 'Sesotho sa Leboa' },
    { code: 'diq', name: 'Zazaki', nativeName: 'Zazaki' },
    { code: 'hak', name: 'Hakka', nativeName: 'Hak-kâ-fa / 客家話' },
    { code: 'se', name: 'Northern Sami', nativeName: 'Sámegiella' },
    { code: 'mi', name: 'Maori', nativeName: 'Māori' },
    { code: 'bcl', name: 'Central_Bicolano', nativeName: 'Bikol' },
    { code: 'nds-nl', name: 'Dutch Low Saxon', nativeName: 'Nedersaksisch' },
    { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي، سندھی ، सिन्ध' },
    { code: 'gan', name: 'Gan', nativeName: '贛語' },
    { code: 'glk', name: 'Gilaki', nativeName: 'گیلکی' },
    { code: 'vls', name: 'West Flemish', nativeName: 'West-Vlams' },
    { code: 'rue', name: 'Rusyn', nativeName: 'русиньскый язык' },
    { code: 'bo', name: 'Tibetan', nativeName: 'བོད་སྐད' },
    { code: 'wuu', name: 'Wu', nativeName: '吴语' },
    { code: 'fiu-vro', name: 'Võro', nativeName: 'Võro' },
    { code: 'szl', name: 'Silesian', nativeName: 'Ślůnski' },
    { code: 'co', name: 'Corsican', nativeName: 'Corsu' },
    { code: 'vep', name: 'Vepsian', nativeName: 'VepsÃ¤n' },
    { code: 'sc', name: 'Sardinian', nativeName: 'Sardu' },
    { code: 'lrc', name: 'Northern Luri', nativeName: 'لۊری شومالی' },
    { code: 'tk', name: 'Turkmen', nativeName: 'تركمن / Туркмен' },
    { code: 'csb', name: 'Kashubian', nativeName: 'Kaszëbsczi' },
    { code: 'crh', name: 'Crimean Tatar', nativeName: 'Qırımtatarca' },
    { code: 'zh-classical', name: 'Classical Chinese', nativeName: '古文 / 文言文' },
    { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
    { code: 'gv', name: 'Manx', nativeName: 'Gaelg' },
    { code: 'kv', name: 'Komi', nativeName: 'Коми' },
    { code: 'frr', name: 'North Frisian', nativeName: 'Nordfriisk' },
    { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
    { code: 'lad', name: 'Ladino', nativeName: 'Dzhudezmo' },
    { code: 'zea', name: 'Zeelandic', nativeName: 'Zeêuws' },
    { code: 'so', name: 'Somali', nativeName: 'Soomaaliga' },
    { code: 'cdo', name: 'Min Dong', nativeName: 'Mìng-dĕ̤ng-ngṳ̄' },
    { code: 'ace', name: 'Acehnese', nativeName: 'Bahsa Acèh' },
    { code: 'ay', name: 'Aymara', nativeName: 'Aymar' },
    { code: 'udm', name: 'Udmurt', nativeName: 'Удмурт кыл' },
    { code: 'stq', name: 'Saterland Frisian', nativeName: 'Seeltersk' },
    { code: 'kw', name: 'Cornish', nativeName: 'Kernewek/Karnuack' },
    { code: 'nrm', name: 'Norman', nativeName: 'Nouormand/Normaund' },
    { code: 'ie', name: 'Interlingue', nativeName: 'Interlingue' },
    { code: 'koi', name: 'Komi-Permyak', nativeName: 'Перем Коми (Perem Komi)' },
    { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch' },
    { code: 'pcd', name: 'Picard', nativeName: 'Picard' },
    { code: 'myv', name: 'Erzya', nativeName: 'Эрзянь (Erzjanj Kelj)' },
    { code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇر تىلى' },
    { code: 'lij', name: 'Ligurian', nativeName: 'Líguru' },
    { code: 'lez', name: 'Lezgian', nativeName: 'ÐÐµÐ·Ð³Ð¸ ÑÐÐ°Ð»' },
    { code: 'mt', name: 'Maltese', nativeName: 'Malti' },
    { code: 'fur', name: 'Friulian', nativeName: 'Furlan' },
    { code: 'gn', name: 'Guarani', nativeName: 'Avañe\'ẽ' },
    { code: 'dsb', name: 'Lower Sorbian', nativeName: 'Dolnoserbski' },
    { code: 'gom', name: 'Goan Konkani', nativeName: 'गोंयची कोंकणी / Gõychi Konknni' },
    { code: 'dv', name: 'Divehi', nativeName: 'ދިވެހިބަސް' },
    { code: 'cbk-zam', name: 'Zamboanga Chavacano', nativeName: 'Chavacano de Zamboanga' },
    { code: 'ext', name: 'Extremaduran', nativeName: 'Estremeñu' },
    { code: 'ang', name: 'Anglo-Saxon', nativeName: 'Englisc' },
    { code: 'kab', name: 'Kabyle', nativeName: 'Taqbaylit' },
    { code: 'ksh', name: 'Ripuarian', nativeName: 'Ripoarisch' },
    { code: 'mwl', name: 'Mirandese', nativeName: 'Mirandés' },
    { code: 'ln', name: 'Lingala', nativeName: 'Lingala' },
    { code: 'gag', name: 'Gagauz', nativeName: 'Gagauz' },
    { code: 'sn', name: 'Shona', nativeName: 'chiShona' },
    { code: 'nv', name: 'Navajo', nativeName: 'Diné bizaad' },
    { code: 'frp', name: 'Franco-Provençal/Arpitan', nativeName: 'Arpitan' },
    { code: 'pag', name: 'Pangasinan', nativeName: 'Pangasinan' },
    { code: 'pi', name: 'Pali', nativeName: 'पाऴि' },
    { code: 'av', name: 'Avar', nativeName: 'Авар' },
    { code: 'xal', name: 'Kalmyk', nativeName: 'Хальмг' },
    { code: 'pfl', name: 'Palatinate German', nativeName: 'Pfälzisch' },
    { code: 'krc', name: 'Karachay-Balkar', nativeName: 'Къарачай-Малкъар (Qarachay-Malqar)' },
    { code: 'lo', name: 'Lao', nativeName: 'ລາວ' },
    { code: 'haw', name: 'Hawaiian', nativeName: 'Hawai`i' },
    { code: 'kaa', name: 'Karakalpak', nativeName: 'Qaraqalpaqsha' },
    { code: 'olo', name: 'Livvi-Karelian', nativeName: 'livvin kieli' },
    { code: 'bxr', name: 'Buryat (Russia)', nativeName: 'Буряад' },
    { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
    { code: 'pdc', name: 'Pennsylvania German', nativeName: 'Deitsch' },
    { code: 'pap', name: 'Papiamentu', nativeName: 'Papiamentu' },
    { code: 'bjn', name: 'Banjar', nativeName: 'Bahasa Banjar' },
    { code: 'to', name: 'Tongan', nativeName: 'faka Tonga' },
    { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut' },
    { code: 'nov', name: 'Novial', nativeName: 'Novial' },
    { code: 'arc', name: 'Aramaic', nativeName: 'ܐܪܡܝܐ' },
    { code: 'jam', name: 'Jamaican', nativeName: 'Patois' },
    { code: 'kbd', name: 'Kabardian Circassian', nativeName: 'Адыгэбзэ (Adighabze)' },
    { code: 'ha', name: 'Hausa', nativeName: 'هَوُسَ' },
    { code: 'tet', name: 'Tetum', nativeName: 'Tetun' },
    { code: 'tyv', name: 'Tuvan', nativeName: 'тыва дыл' },
    { code: 'ki', name: 'Kikuyu', nativeName: 'Gĩkũyũ' },
    { code: 'tpi', name: 'Tok Pisin', nativeName: 'Tok Pisin' },
    { code: 'ig', name: 'Igbo', nativeName: 'Igbo' },
    { code: 'na', name: 'Nauruan', nativeName: 'dorerin Naoero' },
    { code: 'ab', name: 'Abkhazian', nativeName: 'Аҧсуа' },
    { code: 'lbe', name: 'Lak', nativeName: 'Лакку' },
    { code: 'roa-rup', name: 'Aromanian', nativeName: 'Armãneashce' },
    { code: 'jbo', name: 'Lojban', nativeName: 'Lojban' },
    { code: 'ty', name: 'Tahitian', nativeName: 'Reo Mā`ohi' },
    { code: 'kg', name: 'Kongo', nativeName: 'KiKongo' },
    { code: 'za', name: 'Zhuang', nativeName: 'Cuengh' },
    { code: 'mdf', name: 'Moksha', nativeName: 'Мокшень (Mokshanj Kälj)' },
    { code: 'lg', name: 'Luganda', nativeName: 'Luganda' },
    { code: 'wo', name: 'Wolof', nativeName: 'Wolof' },
    { code: 'srn', name: 'Sranan', nativeName: 'Sranantongo' },
    { code: 'zu', name: 'Zulu', nativeName: 'isiZulu' },
    { code: 'bi', name: 'Bislama', nativeName: 'Bislama' },
    { code: 'ltg', name: 'Latgalian', nativeName: 'Latgaļu' },
    { code: 'chr', name: 'Cherokee', nativeName: 'ᏣᎳᎩ' },
    { code: 'tcy', name: 'Tulu', nativeName: 'ತುಳು ಭಾಷೆ' },
    { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa' },
    { code: 'om', name: 'Oromo', nativeName: 'Oromoo' },
    { code: 'tn', name: 'Tswana', nativeName: 'Setswana' },
    { code: 'chy', name: 'Cheyenne', nativeName: 'Tsetsêhestâhese' },
    { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa' },
    { code: 'tw', name: 'Twi', nativeName: 'Twi' },
    { code: 'cu', name: 'Old Church Slavonic', nativeName: 'Словѣньскъ' },
    { code: 'rmy', name: 'Romani', nativeName: 'romani - रोमानी' },
    { code: 'tum', name: 'Tumbuka', nativeName: 'chiTumbuka' },
    { code: 'pih', name: 'Norfolk', nativeName: 'Norfuk' },
    { code: 'rn', name: 'Kirundi', nativeName: 'Kirundi' },
    { code: 'pnt', name: 'Pontic', nativeName: 'Ποντιακά' },
    { code: 'ss', name: 'Swati', nativeName: 'SiSwati' },
    { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru' },
    { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan' },
    { code: 'ady', name: 'Adyghe', nativeName: 'адыгабзэ' },
    { code: 'mo', name: 'Moldovan', nativeName: 'Молдовеняскэ' },
    { code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga' },
    { code: 'iu', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
    { code: 'st', name: 'Sesotho', nativeName: 'Sesotho' },
    { code: 'ny', name: 'Chichewa', nativeName: 'Chi-Chewa' },
    { code: 'fj', name: 'Fijian', nativeName: 'Na Vosa Vakaviti' },
    { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe' },
    { code: 'ak', name: 'Akan', nativeName: 'Akana' },
    { code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी / كشميري' },
    { code: 'sg', name: 'Sango', nativeName: 'Sängö' },
    { code: 'ik', name: 'Inupiak', nativeName: 'Iñupiak' },
    { code: 've', name: 'Venda', nativeName: 'Tshivenda' },
    { code: 'dz', name: 'Dzongkha', nativeName: 'ཇོང་ཁ' },
    { code: 'ff', name: 'Fula', nativeName: 'Fulfulde' },
    { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ' },
    { code: 'cr', name: 'Cree', nativeName: 'Nehiyaw' },
    { code: 'ng', name: 'Ndonga', nativeName: 'Oshiwambo' },
    { code: 'cho', name: 'Choctaw', nativeName: 'Choctaw' },
    { code: 'mh', name: 'Marshallese', nativeName: 'Ebon' },
    { code: 'kj', name: 'Kuanyama', nativeName: 'Kuanyama' },
    { code: 'ii', name: 'Sichuan Yi', nativeName: 'ꆇꉙ' },
    { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu' },
    { code: 'aa', name: 'Afar', nativeName: 'Afar' },
    { code: 'mus', name: 'Muscogee', nativeName: 'Muskogee' },
    { code: 'hz', name: 'Herero', nativeName: 'Otsiherero' },
    { code: 'kr', name: 'Kanuri', nativeName: 'Kanuri' }
  ];
  let userLanguages = [];

  return service;

  //

  function getLanguagesList() {
    return languageList;
  }

  function getNativeLanguages(code) {
    return countryLanguagesList[code];
  }

  function getUserLanguages() {
    if (userLanguages.length) { return angular.copy(userLanguages); }

    const ls = localStorageService.get('languages');
    let def = navigator.languages
      ? navigator.languages[0]
      : (navigator.language || navigator.userLanguage);
    def = def.split('-')[0];

    const langs = ls || [def];
    if (!langs.includes('en')) { langs.push('en'); }
    userLanguages = langs.map(lang => $filter('filter')(languageList, lang)[0]);
    return angular.copy(userLanguages);
  }

  function setUserLanguages(langs) {
    const list = langs.filter(lang => lang).map(lang => lang.code);
    localStorageService.set('languages', list);
    userLanguages = langs;
    return $q.when(true);
  }
};

export default () => {
  angular
    .module('monumental')
    .factory('langService', LangService);
};
